//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SalesStatisticsService.Contracts.Entity;

namespace SalesStatisticsService.Entity
{
    public partial class Sale : ISaleEntity
    {
        public int Id { get; set; }
        public int ManagerId { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
